### ISSUE TITLE
Small fix. No synchronization with Update()

### ISSUE THREAD

**Issue by Xsanf** [eublefar/LLAMASharpUnityDemo#1]
Your example assumes stream output. But in reality the Output field will be shown only after the output is completely completed.

```
await foreach (var token in ChatConcurrent(
                session.ChatAsync(
                    bobPrompt, 
                    new InferenceParams() 
                    { 
                        Temperature = 0.6f, 
                        AntiPrompts = new List<string> { "User:" } 
                    }
                )
            ))
            {
                Output.text += token;
            }
```

Correction - Now the output will be added after each Output.text += token;

```
await foreach (var token in ChatConcurrent(
                session.ChatAsync(
                    bobPrompt, 
                    new InferenceParams() 
                    { 
                        Temperature = 0.6f, 
                        AntiPrompts = new List<string> { "User:" } 
                    }
                )
            ))
            {
                Output.text += token;
                await UniTask.NextFrame();
            }
```

**Comment by eublefar** [comment]
Thanks a lot for noticing this!
Would you like to create a pull request with this fix?
(If not I'll fix it a bit later myself)

**Comment by Xsanf** [comment]
Thank you very much for the example. Of course, fix it yourself. There's just one line.
In fact, there are still questions. in NuGet Some examples do not see all libraries in the namespace. This mainly concerns the Semantic Kernel. Of course, this is not the final version, but unfortunately this is my first time using NuGet, so it’s not obvious to me how to configure this.

For an example in Unity, I tried to port the KernelMemory.cs example. Imported into NuGet but not visible in the namespace:

using LLamaSharp.KernelMemory;
using Microsoft.KernelMemory;
using Microsoft.KernelMemory.Handlers;

If you understand the essence of the problem, I would be grateful for your advice.

I'm using version 0.8.1

**Comment by eublefar** [comment]
I had the same issue with OnnxRuntime nuget. I have no idea why though. I think building it manually for Unity's target runtime helped with the issue I was having.

**Comment by Xsanf** [comment]
[eublefar](https://github.com/eublefar) Thanks for the advice. I'll probably deal with the final version. Moreover, LaamaSharp himself does not cause such problems.
