### ISSUE TITLE
Model Speed

### ISSUE THREAD

**Issue by sania96** [eublefar/LLAMASharpUnityDemo#3]
Hi, Great Work!
my model is taking too much time to generate one token and for a sentence i it takes 30 minutes how can i make it faster?

**Comment by eublefar** [comment]
Hi
Depends on the hardware. 30 minutes is A LOT tho, even on the older desktop CPU I have it runs faster. Maybe you don't have enough RAM and it spills into hard drive or something? If you have nvidia GPU, you could use CUDA backend to speed things up. 
Sometimes when I mess up llama grammars for constrained generation it can also cause some bug where it doesn't outright fail but takes forever to generate anything, so there is also that to check if you use that feature.

**Comment by sania96** [comment]
yes i have 4gb ram only, but i have nvidia gpu i will try run on cuda backend then,
And how can i check llama grammars if there is any bug or not.

Thanks for your help, mean alot.

**Comment by eublefar** [comment]
If you are using LLamaSharp executors without any additional grammars - don't worry about it.
If you are writing your own grammars I suggest you test it using llama.cpp server first (it has UI) just to see if it causes any issues. (e.g. run your prompt w/o and with grammar)
