### ISSUE TITLE
Error with new version of llamasharp

### ISSUE THREAD

**Issue by sania96** [eublefar/LLAMASharpUnityDemo#4]
i cannot use this project as llamasharp is updated, i am having this error:

Assets\LlamaSharpTestScript.cs(53,21): error CS1503: Argument 1: cannot convert from 'string' to 'LLama.Common.ChatHistory.Message'

and 

Assets\LlamaSharpTestScript.cs(54,21): error CS1503: Argument 2: cannot convert from 'LLama.Common.InferenceParams' to 'bool'

can you please tell me replacement of code?

**Comment by eublefar** [comment]
Hey

I've just updated it to the latest version and also added example of switching between multiple sessions.

Enjoy!

**Comment by sania96** [comment]
Hey, Thanks You are very Helping.
