### ISSUE TITLE
giving input in different roles

### ISSUE THREAD

**Issue by sania96** [eublefar/LLAMASharpUnityDemo#5]
is there anyway to use this to give input and output as json format? user and assistant and system prompt separately?

**Comment by eublefar** [comment]
Could you elaborate with some example of what you are trying to do?

**Comment by sania96** [comment]
I meant to say that:
as in the example the model is generating text along with "Bob: and "\nUser:" to take next input I want that the model should only be responsible for generating text against user input instead of generating any extra characters for next input.

like giving input prompt and getting output text:
authorrole.user's text can be accessed anytime and authorrole.assistant text also can be extracted.


inshort, as in example of text-with-bob.json instead of using text-with-bob.txt.

i hope this clarifies

**Comment by eublefar** [comment]
You should check the [LLamaSharp](https://github.com/SciSharp/LLamaSharp) examples or create an issue on their github as I am not the creator of the project and I am unsure how to do it. My gues is that it's something to do with input/output/history transforms.
