### ISSUE TITLE
crashing when entering play mode. 

### ISSUE THREAD

**Issue by Tonierbobcat** [eublefar/LLAMASharpUnityDemo#7]
I am currently testing on the llamasharpdemo project and I got everything set up correctly. and I noticed the text generation was pain painstakingly slow. so I opted to install the llama cuda dll and renamed it to libllama.dll. I thought this would fix my issue but I never got a change to test because it crashed when entering play mode. 

I dragged in to cuda runtime dlls from the llama CU12.2.0.zip into my assets folder and I am still getting the crash.

**Comment by Tonierbobcat** [comment]
fixed by making sure that the llamasharp is the sameversion as the cuda. for future references. both the llamasharp and llama backend need to be the same version.

**Comment by eublefar** [comment]
Added comment to readme to avoid confusion. All versions must be the same (llamasharp - backend, backend cuda - cuda toolkit installed, etc)
